dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel_0.18.1-linux-x86_64.deb
  - echo "4c2cd0a71ab1b65753aeb757af36bd6ebde9da4e53183525a1e1849c2542fdda  bazel_0.18.1-linux-x86_64.deb" > bazel_0.3.1-linux-x86_64.deb.sha256
  - sha256sum -c bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.18.1-linux-x86_64.deb

script:
  - bazel test test