# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook/addressbook.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from addressbook import person_pb2 as addressbook_dot_person__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook/addressbook.proto',
  package='playground.addressbook',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1d\x61\x64\x64ressbook/addressbook.proto\x12\x16playground.addressbook\x1a\x18\x61\x64\x64ressbook/person.proto\"=\n\x0b\x41\x64\x64ressBook\x12.\n\x06people\x18\x01 \x03(\x0b\x32\x1e.playground.addressbook.Personb\x06proto3')
  ,
  dependencies=[addressbook_dot_person__pb2.DESCRIPTOR,])




_ADDRESSBOOK = _descriptor.Descriptor(
  name='AddressBook',
  full_name='playground.addressbook.AddressBook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='playground.addressbook.AddressBook.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=144,
)

_ADDRESSBOOK.fields_by_name['people'].message_type = addressbook_dot_person__pb2._PERSON
DESCRIPTOR.message_types_by_name['AddressBook'] = _ADDRESSBOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressBook = _reflection.GeneratedProtocolMessageType('AddressBook', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSBOOK,
  __module__ = 'addressbook.addressbook_pb2'
  # @@protoc_insertion_point(class_scope:playground.addressbook.AddressBook)
  ))
_sym_db.RegisterMessage(AddressBook)


# @@protoc_insertion_point(module_scope)
