# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook/phone_number.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addressbook/phone_number.proto',
  package='playground.addressbook',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x61\x64\x64ressbook/phone_number.proto\x12\x16playground.addressbook\"N\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.playground.addressbook.PhoneType*+\n\tPhoneType\x12\x08\n\x04HOME\x10\x00\x12\n\n\x06MOBILE\x10\x01\x12\x08\n\x04WORK\x10\x02\x62\x06proto3')
)

_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='playground.addressbook.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOME', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=138,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_PHONETYPE)

PhoneType = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE)
HOME = 0
MOBILE = 1
WORK = 2



_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='playground.addressbook.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='playground.addressbook.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='playground.addressbook.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=136,
)

_PHONENUMBER.fields_by_name['type'].enum_type = _PHONETYPE
DESCRIPTOR.message_types_by_name['PhoneNumber'] = _PHONENUMBER
DESCRIPTOR.enum_types_by_name['PhoneType'] = _PHONETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), dict(
  DESCRIPTOR = _PHONENUMBER,
  __module__ = 'addressbook.phone_number_pb2'
  # @@protoc_insertion_point(class_scope:playground.addressbook.PhoneNumber)
  ))
_sym_db.RegisterMessage(PhoneNumber)


# @@protoc_insertion_point(module_scope)
